### ISSUE TITLE
Update icon

### ISSUE THREAD

**Issue by keunes** [jonhil/recipe-franz-mailbox.org#2]
Hello,
Mailbox.org has a new logo, which should ideally be reflected reflected in the recipe. I contacted their helpdesk and they provided me with the svg :) I'll try to submit a PR to get the new icon in.

**Comment by keunes** [comment]
Ok, that worked, I think. It'd be great if you could accept @jonhil :)
(cf. getferdi/sponsors-only#2034)

**Comment by jonhil** [comment]
Thanks @keunes for the pr.
Is merged.
